services:
  frontend-balancer:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - frontend1
      - frontend2
      - frontend3
    networks:
      - app-network
      - monitoring-network

  frontend1:
    build:
      context: ./front
      dockerfile: Dockerfile
    networks:
      - app-network

  frontend2:
    build:
      context: ./front
      dockerfile: Dockerfile
    networks:
      - app-network

  frontend3:
    build:
      context: ./front
      dockerfile: Dockerfile
    networks:
      - app-network

  reservation-nginx-exporter:
    container_name: reservation-nginx-exporter
    image: nginx/nginx-prometheus-exporter
    command:
      - -nginx.scrape-uri=http://frontend-balancer/metrics
    ports:
      - "9113:9113"
    networks:
      - app-network
      - monitoring-network
    depends_on:
      - frontend-balancer

networks:
  app-network:
  monitoring-network:
    external: true