version: '3.8'

services:
  admin:
    build:
      context: ./preregistration_project
      dockerfile: Dockerfile
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8001:80"
    networks:
      - app-network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    networks:
      - app-network

  frontend-balancer:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - frontend
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network: