version: '3.8'

services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - app-network

  backend:    # 이 부분의 들여쓰기가 잘못됨 (앞에 공백이 하나 있었음)
    build:
      context: ./back
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/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"
    networks:
      - app-network
    ports:
      - "8082:8000"
    depends_on:
      - db

  admin:
    build:
      context: ./preregistration_project
      dockerfile: Dockerfile
    environment:
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
    ports:
      - "8081:80"
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data: