services:
  admin:
    build:
      context: ./preregistration_project
      dockerfile: Dockerfile
    environment:
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8081:80"
    networks:
      - app-network
    depends_on:
      - db-master

  db-master:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db/primary:/etc/postgresql/conf.d
      - db-master-data:/var/lib/postgresql/data
    networks:
      - app-network
      - monitoring-network

  db-replica:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db/standby:/etc/postgresql/conf.d
      - db-replica-data:/var/lib/postgresql/data
    networks:
      - app-network
      - monitoring-network
    depends_on:
      - db-master

  reservation-postgres-exporter:
    container_name: reservation-postgres-exporter
    image: prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db-master:5432/${POSTGRES_DB}?sslmode=disable"
    ports:
      - "9187:9187"
    networks:
      - app-network
      - monitoring-network
    depends_on:
      - db-master

  reservation-cadvisor:
    container_name: reservation-cadvisor
    image: gcr.io/cadvisor/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - "8090:8080"
    networks:
      - app-network
      - monitoring-network

volumes:
  db-master-data:
  db-replica-data:

networks:
  app-network:
  monitoring-network:
    external: true