# Generated by Django 5.1 on 2024-09-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistrations', '0002_alter_preregistration_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preregistration',
            name='phone',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
